openapi: 3.2.0
info:
  version: v1
  title: Nexla Rest Custom Runtimes API
  termsOfService: https://nexla.com/terms-of-service/
  contact:
    name: Nexla Support
    url: https://docs.nexla.com
    email: support@nexla.com
  license:
    name: Nexla
    url: https://nexla.com
  x-logo:
    url: https://cdn.nexla.io/ui/assets/brand/v2/nexla-logo-color-portrait.svg
    backgroundColor: '#ffffff'
  description: '# Introduction


    The Nexla API is a REST-ful API used to easily create and manage resources in Nexla in ways that best fit any use case. It can be used to configure and monitor data flows for different data-integration use cases and to perform all aspects of data engineering automation offered by the Nexla platform.


    The Nexla API supports all data flow-creation and -management actions in the platform, as well as administrative user- and organization-level account-management tasks. Note that all other client packages, such as the Nexla CLI and Nexla UI, also connect to the overall Nexla infrastructure through the Nexla API.


    The API references in this document lists all API endpoints and the corresponding payloads.


    Check out the [API Developer Guides](https://developers.nexla.com/docs/nexla-api) to view guides and tutorials for recommended use cases for different endpoints.


    # API Data Format and Versions


    The API uses JSON for all data exchanges.


    You __should__ specify the API version that should be used in the Accept header of each request. For example, to access Version 1 of the API, the Accept header should be the following:

    ```

    Accept: application/vnd.nexla.api.v1+json

    ```


    The Nexla API also supports a generic version header, which will default your access to the latest version of the data source/destination API.



    ```

    Accept: application/json

    ```


    # Authentication


    Most Nexla API endpoints require `Bearer Token` authentication mechanism for making an authenticated request to the API. While this token can be generated programmatically outside Nexla UI by starting a session with an `api_key`, unless unavoidable, we recommend starting your session from the Nexla UI and using the `Nexla Session Token` from the Nexla UI as the Authorization header for calls to the Nexla API.


    <SecurityDefinitions />'
servers:
- url: https://{nexla-api-host}
  variables:
    nexla-api-host:
      default: dataops.nexla.io/nexla-api
      description: Nexla API URL your Nexla instance
security:
- NexlaSessionToken: []
tags:
- name: Custom Runtimes
  description: Operations for managing custom runtimes.
paths:
  /runtimes:
    get:
      tags:
      - Custom Runtimes
      operationId: get_runtimes
      summary: Get all Custom Runtimes
      description: Retrieves a list of all custom runtimes defined for the organization.
      responses:
        '200':
          $ref: '#/components/responses/runtimes_many'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
    post:
      tags:
      - Custom Runtimes
      operationId: create_runtime
      summary: Create a Custom Runtime
      description: Creates a custom runtime with the specified configuration.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RuntimePayload'
      responses:
        '200':
          $ref: '#/components/responses/runtimes_one'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /runtimes/{runtime_id}:
    get:
      tags:
      - Custom Runtimes
      operationId: get_runtime
      summary: Get a custom runtime by ID
      description: Retrieves a custom runtime
      parameters:
      - name: runtime_id
        in: path
        required: true
        description: The ID of the runtime to retrieve
        schema:
          type: integer
      responses:
        '200':
          $ref: '#/components/responses/runtimes_one'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
    put:
      tags:
      - Custom Runtimes
      operationId: update_runtime
      summary: Update a Custom Runtime
      description: Updates a custom runtime.
      parameters:
      - name: runtime_id
        in: path
        required: true
        description: The ID of the runtime to update
        schema:
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RuntimePayload'
      responses:
        '200':
          $ref: '#/components/responses/runtimes_one'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
    delete:
      tags:
      - Custom Runtimes
      operationId: delete_runtime
      summary: Delete a Custom Runtime
      description: Creates a custom runtime with the specified configuration.
      parameters:
      - name: runtime_id
        in: path
        required: true
        description: The ID of the runtime to delete
        schema:
          type: integer
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /runtimes/{runtime_id}/activate:
    put:
      tags:
      - Custom Runtimes
      operationId: activate_runtime
      summary: Activate a Custom Runtime
      description: Activates a custom runtime with the specified ID.
      parameters:
      - name: runtime_id
        in: path
        required: true
        description: The ID of the runtime to activate
        schema:
          type: integer
      responses:
        '200':
          $ref: '#/components/responses/runtimes_one'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /runtimes/{runtime_id}/pause:
    put:
      tags:
      - Custom Runtimes
      operationId: pause_runtime
      summary: Pause a Custom Runtime
      description: Pause a custom runtime with the specified ID.
      parameters:
      - name: runtime_id
        in: path
        required: true
        description: The ID of the runtime to pause
        schema:
          type: integer
      responses:
        '200':
          $ref: '#/components/responses/runtimes_one'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
components:
  schemas:
    org:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email_domain:
          type: string
        email:
          type: 'null'
        client_identifier:
          type: 'null'
    owner:
      type: object
      properties:
        id:
          type: integer
        full_name:
          type: string
        email:
          type: string
          format: email
    RuntimePayload:
      type: object
      properties:
        name:
          type: string
          description: The name of the runtime.
        description:
          type: string
          description: The description of the runtime.
        active:
          type: boolean
          description: Whether the runtime is active or not.
        dockerpath:
          type: string
          description: The path to the Docker image.
        managed:
          type: boolean
          description: Whether the runtime is managed or not.
        config:
          type: object
          description: The configuration of the runtime.
          additionalProperties: true
    Runtime:
      type: object
      properties:
        id:
          type: integer
          description: The unique identifier of the runtime.
        owner:
          $ref: '#/components/schemas/owner'
        org:
          $ref: '#/components/schemas/org'
        name:
          type: string
          description: The name of the runtime.
        description:
          type: string
          description: The description of the runtime.
        created_at:
          type: string
          format: date-time
          description: The date and time when the runtime was created.
        updated_at:
          type: string
          format: date-time
          description: The date and time when the runtime was last updated.
        active:
          type: boolean
          description: Whether the runtime is active or not.
        dockerpath:
          type: string
          description: The path to the Docker image.
        managed:
          type: boolean
          description: Whether the runtime is managed or not.
        config:
          type: object
          description: The configuration of the runtime.
          additionalProperties: true
  responses:
    runtimes_many:
      description: Success
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Runtime'
    runtimes_one:
      description: Success
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Runtime'
  securitySchemes:
    NexlaSessionToken:
      type: http
      scheme: Bearer
      bearerFormat: JWT
      description: "The first step in calling the Nexla API or Nexla CLI is to fetch a Session access token by logging on to your Nexla UI instance. This ensures that your authentication is performed through your organization's preferred Identity Provider.\n\nTo fetch an access token from the Nexla UI, simply go to your Nexla UI instance, and try the route `/token`. For example, if your Nexla UI instance is at `https://dataops.nexla.io`, open `https://dataops.nexla.io/token` in the browser. \n\nThis will automatically route you to a login page, ask you to authenticate using your preferred Identity Provider, and, upon successful authentication, route you to a page where you can copy the Access Token.\n\nUsage format: `Bearer <JWT>`.\n"
    NexlaApiKeyQuery:
      type: apiKey
      name: api_key
      in: query
      description: '> **Important:** Never share your API keys. Keep them guarded and secure. If you think the key has been compromised, you can rotate the API key by calling relevant API Key management endpoints.


        The platform generates a unique API key for this resource. Add the API key as a query parameter to authenticate this request.

        Usage: `?api_key=<api-key>`

        '
    NexlaApiKeyHeader:
      type: http
      scheme: Basic
      description: '> **Important:** Never share your API keys. Keep them guarded and secure. If you think the key has been compromised, you can rotate the API key by calling relevant API Key management endpoints.


        The platform generates a unique API key for this resource. Add the API key as an authorization header to authenticate this request.

        Usage format: `Basic <api-key>`

        '
    basicAuth:
      type: http
      scheme: basic
    GoogleSSOToken:
      type: http
      scheme: Bearer
      bearerFormat: JWT
      description: 'The token that is used when logging into Nexla via Google SSO.

        '
x-tagGroups:
- name: Session
  tags:
  - Session Management
- name: Integrate
  tags:
  - Flows
  - Sources
  - Destinations (Data Sinks)
  - Nexsets (Data Sets)
  - Credentials
  - Data Maps
  - Code Containers
  - Transforms
  - Projects
- name: Monitor
  tags:
  - Notifications
  - Metrics
  - Audit Logs
  - Quarantine Settings
- name: Collaborate
  tags:
  - Access Control
- name: Account Management
  tags:
  - Organizations
  - Users
  - User Settings
  - Teams
  - Gen AI Configs
- name: Real-Time Events
  tags:
  - Webhooks
- name: Rate Limiting
  tags:
  - Limits
- name: Marketplace
  tags:
  - Marketplace
- name: Self Sign-Up
  tags:
  - Self Sign-Up
  - Self Sign-Up Admin
- name: Async Tasks
  tags:
  - Async Tasks
